# Generated by Django 6.0.4 on 2026-05-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quartier', models.CharField(blank=True, max_length=200)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('est_baptise', models.BooleanField(default=False)),
                ('est_confirme', models.BooleanField(default=False)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='groupes.groupe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membre_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Sacrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bapteme', 'Baptême'), ('mariage', 'Mariage'), ('confirmation', 'Confirmation'), ('communion', 'Communion'), ('funerailles', 'Funérailles')], max_length=20)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacrements', to='membres.membre')),
                ('officiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacrements_officies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sacrement',
                'verbose_name_plural': 'Sacrements',
                'ordering': ['-date'],
            },
        ),
    ]
