# Generated by Django 6.0.4 on 2026-07-10 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('quartier', models.CharField(blank=True, max_length=200, null=True)),
                ('est_baptise', models.BooleanField(default=False)),
                ('est_confirme', models.BooleanField(default=False)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='groupes.groupe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Sacrement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('bapteme', 'Baptême'), ('mariage', 'Mariage'), ('confirmation', 'Confirmation'), ('communion', 'Communion'), ('funerailles', 'Funérailles')], max_length=20)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacrements', to='membres.membre')),
                ('officiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacrements_officies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sacrement',
                'verbose_name_plural': 'Sacrements',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='sacrement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='membres.sacrement'),
        ),
        migrations.AddIndex(
            model_name='sacrement',
            index=models.Index(fields=['type'], name='membres_sac_type_35bb62_idx'),
        ),
        migrations.AddIndex(
            model_name='sacrement',
            index=models.Index(fields=['date'], name='membres_sac_date_373d20_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['nom', 'prenom'], name='membres_mem_nom_849d64_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['date_naissance'], name='membres_mem_date_na_4a8938_idx'),
        ),
    ]
