# Generated by Django 6.0.4 on 2026-05-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('messe', 'Messe'), ('fete_liturgique', 'Fête liturgique'), ('reunion', 'Réunion'), ('kermesse', 'Kermesse'), ('reservation', 'Réservation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('est_inscription_requise', models.BooleanField(default=False)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='evenements.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'unique_together': {('evenement', 'membre')},
            },
        ),
    ]
