# Generated by Django 6.0.4 on 2026-07-10 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('messe', 'Messe'), ('fete_liturgique', 'Fête liturgique'), ('reunion', 'Réunion'), ('kermesse', 'Kermesse'), ('reservation', 'Réservation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('est_inscription_requise', models.BooleanField(default=False)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='evenements.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['type'], name='evenement_type_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_debut'], name='evenement_date_debut_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('evenement', 'membre')},
        ),
    ]
