# Generated by Django 6.0.4 on 2026-07-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
        ('groupes', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='groupes_invites',
            field=models.ManyToManyField(blank=True, related_name='evenements_invites', to='groupes.groupe'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='invite_tous',
            field=models.BooleanField(default=False, verbose_name='Convier toute la paroisse'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='membres_invites',
            field=models.ManyToManyField(blank=True, related_name='evenements_invites', to='membres.membre'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='roles_invites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
