# Generated by Django 6.0.4 on 2026-07-16 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='groupes_diriges', to=settings.AUTH_USER_MODEL),
        ),
    ]
