# Generated by Django 6.0.4 on 2026-06-27 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['nom'], name='groupe_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['responsable'], name='groupe_responsable_idx'),
        ),
    ]
