# Generated by Django 6.0.4 on 2026-05-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=10)),
                ('categorie', models.CharField(choices=[('quete', 'Quête'), ('don', 'Don'), ('location', 'Location'), ('librairie', 'Librairie'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
